import type { Metadata } from 'next'
import Link from 'next/link'

import { contactEmail } from '@/components/landing/landing-copy'

export const metadata: Metadata = {
  title: 'Privacy Policy — Astrail',
  description:
    'How Astrail collects, uses, shares, and protects your data during the beta.',
}

const UPDATED = 'August 2026'

/* Beta-stage privacy policy. Plain-language and accurate to what the app
   actually does today. NOTE: reviewed by the team, not yet by a lawyer —
   have counsel check this before the public launch. */
export default function PrivacyPage() {
  return (
    <main className="mx-auto min-h-screen max-w-3xl px-6 py-20 text-[color:var(--ink-600,#4a4a4a)]">
      <Link
        href="/"
        className="text-sm text-[color:var(--ink-400,#8a8a8a)] hover:underline"
      >
        &larr; Back to Astrail
      </Link>

      <h1 className="mt-8 text-3xl font-semibold text-[color:var(--ink-900,#1a1a1a)]">
        Privacy Policy
      </h1>
      <p className="mt-2 text-sm text-[color:var(--ink-400,#8a8a8a)]">
        Last updated: {UPDATED}
      </p>

      <div className="mt-10 space-y-8 text-[15px] leading-relaxed">
        <section>
          <p>
            Astrail is an AI-native travel planner, currently in beta. This
            policy explains what we collect, why, who we share it with, and the
            control you have over it. We keep it plain because you should
            actually understand it.
          </p>
        </section>

        <Section title="What we collect">
          <ul className="list-disc space-y-2 pl-5">
            <li>
              <b>Account details</b> — your email address, and (if you use Google
              sign-in) your name and avatar. We use passwordless sign-in, so we
              never store a password.
            </li>
            <li>
              <b>What you give us to plan</b> — the Instagram Reel and post links
              you paste, your dates, budget, origin, and free-text preferences, plus
              the trips and itineraries Astrail generates for you.
            </li>
            <li>
              <b>Your travel taste</b> — preferences you tell us during
              onboarding and ones Astrail infers as you use it (pace, budget,
              food, neighborhoods), so plans get sharper over time.
            </li>
            <li>
              <b>Feedback</b> — ratings, corrections, and messages you send us.
            </li>
            <li>
              <b>Technical &amp; usage data</b> — basic logs and request counts
              needed to run the service, prevent abuse, and enforce limits.
            </li>
          </ul>
        </Section>

        <Section title="Public content you link to">
          <p>
            When you paste a Reel or post link, Astrail reads the publicly
            available content of that post to extract the places mentioned. We do not log
            into Instagram as you, and we do not access private accounts or
            content that isn&rsquo;t public. Only submit links you have the right
            to share.
          </p>
        </Section>

        <Section title="How we use your data">
          <p>
            To run the planning pipeline (extract places, verify them, build the
            itinerary), personalize your results, keep your saved trips, respond
            to feedback, secure the service, and — occasionally — email you about
            your account or the beta. We do <b>not</b> sell your personal data,
            and we don&rsquo;t run ads.
          </p>
        </Section>

        <Section title="Who processes your data">
          <p>
            We use a small set of trusted providers to operate Astrail. Each
            handles only what it needs to:
          </p>
          <ul className="mt-3 list-disc space-y-1.5 pl-5">
            <li>
              <b>Supabase</b> — authentication, database, and file storage
            </li>
            <li>
              <b>OpenAI</b> — the AI agents that plan your trip
            </li>
            <li>
              <b>Apify</b> — retrieving public reel and post content you link
            </li>
            <li>
              <b>Mapbox</b> — maps and geocoding
            </li>
            <li>
              <b>mem0</b> — storing your remembered travel preferences
            </li>
            <li>
              <b>Resend</b> — sending account emails
            </li>
            <li>
              <b>Vercel, Render, and Cloudflare</b> — hosting and delivery
            </li>
          </ul>
        </Section>

        <Section title="AI-generated content">
          <p>
            Astrail&rsquo;s recommendations are generated by AI from public
            content and third-party data. We work hard to attach evidence to
            every stop, but results can still be incomplete or wrong — always
            confirm key details (hours, prices, safety, bookings) before you
            rely on them.
          </p>
        </Section>

        <Section title="Your rights and choices">
          <p>
            You can access, correct, or delete your data. To delete your
            account, email us at{' '}
            <a
              className="font-medium text-[color:var(--ink-900,#1a1a1a)] underline"
              href={`mailto:${contactEmail}?subject=Delete%20my%20Astrail%20account`}
            >
              {contactEmail}
            </a>
            . Deletion removes your account, saved reels, and generated trips,
            and erases your remembered preferences (including your mem0 memory).
            Depending on where you live, you may also have rights under the GDPR
            or CCPA/CPRA, including the right to access your data and to opt out
            of any sharing — we honor these on request.
          </p>
        </Section>

        <Section title="Cookies">
          <p>
            We use an essential cookie to keep you signed in. We keep any
            analytics minimal and use it only to understand and improve the beta.
          </p>
        </Section>

        <Section title="Data retention">
          <p>
            We keep your data while your account is active. When you ask us to
            delete it, we remove it from our systems and instruct our processors
            to do the same, except where we&rsquo;re legally required to retain
            limited records.
          </p>
        </Section>

        <Section title="Children">
          <p>
            Astrail isn&rsquo;t intended for anyone under 16. If you believe a
            child has given us data, contact us and we&rsquo;ll remove it.
          </p>
        </Section>

        <Section title="Changes to this policy">
          <p>
            As Astrail grows out of beta (including when hotel booking arrives),
            we&rsquo;ll update this policy and change the date above. Material
            changes will be communicated in-app or by email.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about your privacy? Email{' '}
            <a
              className="font-medium text-[color:var(--ink-900,#1a1a1a)] underline"
              href={`mailto:${contactEmail}`}
            >
              {contactEmail}
            </a>
            .
          </p>
        </Section>
      </div>
    </main>
  )
}

function Section({
  title,
  children,
}: {
  title: string
  children: React.ReactNode
}) {
  return (
    <section>
      <h2 className="text-xl font-semibold text-[color:var(--ink-900,#1a1a1a)]">
        {title}
      </h2>
      <div className="mt-3">{children}</div>
    </section>
  )
}
