import type { Metadata } from 'next'
import Link from 'next/link'

import { contactEmail } from '@/components/landing/landing-copy'

export const metadata: Metadata = {
  title: 'Terms of Service — Astrail',
  description: 'The terms for using Astrail during the beta.',
}

const UPDATED = 'August 2026'

/* Beta-stage terms of service. Accurate to how the beta actually works (free,
   no payments, 25 discretionary seats, AI-generated content). NOTE: reviewed by
   the team, not yet by a lawyer — have counsel check this before public launch. */
export default function TermsPage() {
  return (
    <main className="mx-auto min-h-screen max-w-3xl px-6 py-20 text-[color:var(--ink-600,#4a4a4a)]">
      <Link
        href="/"
        className="text-sm text-[color:var(--ink-400,#8a8a8a)] hover:underline"
      >
        &larr; Back to Astrail
      </Link>

      <h1 className="mt-8 text-3xl font-semibold text-[color:var(--ink-900,#1a1a1a)]">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-[color:var(--ink-400,#8a8a8a)]">
        Last updated: {UPDATED}
      </p>

      <div className="mt-10 space-y-8 text-[15px] leading-relaxed">
        <section>
          <p>
            These terms cover your use of Astrail during the beta. By creating an
            account or using the service, you agree to them. If you don&rsquo;t
            agree, please don&rsquo;t use Astrail.
          </p>
        </section>

        <Section title="The service">
          <p>
            Astrail is an AI-native travel planner that turns the travel reels
            you save into an evidence-backed itinerary on a map. It is{' '}
            <b>beta software</b>, provided &ldquo;as is&rdquo;: features may
            change, break, or be paused as we build.
          </p>
        </Section>

        <Section title="Your account">
          <p>
            You sign in with your email or a Google account. Keep your access
            secure and give us accurate information. You&rsquo;re responsible for
            activity under your account.
          </p>
        </Section>

        <Section title="Eligibility">
          <p>
            You must be at least 16 years old and able to form a binding
            contract to use Astrail. Astrail isn&rsquo;t directed at children
            under 16, and we don&rsquo;t knowingly collect their information.
          </p>
        </Section>

        <Section title="Beta access and seats">
          <p>
            Planning is <b>free during the beta</b> — there is no payment
            anywhere in the product. Everyone can create an account and plan
            trips to try Astrail out. <b>Unlimited</b> planning is limited to a
            small number of beta seats (currently 25), which we grant at our
            discretion to active early users. Seats, limits, and features may
            change as the beta evolves.
          </p>
        </Section>

        <Section title="Acceptable use">
          <p>You agree not to:</p>
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li>use Astrail for anything unlawful or harmful;</li>
            <li>
              submit other people&rsquo;s private or personal information, or
              content you don&rsquo;t have the right to share;
            </li>
            <li>
              attempt to reverse-engineer, overload, scrape, or abuse the
              service or the AI behind it;
            </li>
            <li>
              violate the terms of the platforms whose content you link (for
              example, Instagram).
            </li>
          </ul>
        </Section>

        <Section title="AI-generated content">
          <p>
            Itineraries and recommendations are generated by AI from public
            content and third-party data. They may be inaccurate, incomplete, or
            out of date, and they are not professional travel, legal, safety, or
            financial advice. <b>Verify important details yourself</b> before
            acting on them. The beta does not book or pay for anything on your
            behalf.
          </p>
        </Section>

        <Section title="Your content">
          <p>
            You keep your rights to what you submit and to the trips you create.
            You grant Astrail the permission needed to process your inputs and
            operate the service. You confirm you have the right to submit the
            links and information you provide.
          </p>
        </Section>

        <Section title="Our intellectual property">
          <p>
            Astrail, including its software, design, and brand, belongs to us.
            These terms don&rsquo;t give you rights to them beyond using the
            service as intended.
          </p>
        </Section>

        <Section title="Copyright and takedowns">
          <p>
            Astrail plans trips from public content you link, such as Instagram
            reels and posts, and may show a source thumbnail or a short caption
            quote as evidence. If you are a rights holder and believe your
            content appears in Astrail in a way it shouldn&rsquo;t, email{' '}
            <a
              className="font-medium text-[color:var(--ink-900,#1a1a1a)] underline"
              href={`mailto:${contactEmail}?subject=Astrail%20copyright%20concern`}
            >
              {contactEmail}
            </a>{' '}
            and we&rsquo;ll review and remove it.
          </p>
        </Section>

        <Section title="Disclaimers and liability">
          <p>
            Astrail is provided without warranties of any kind. To the fullest
            extent permitted by law, we aren&rsquo;t liable for indirect or
            consequential losses, or for decisions you make based on AI-generated
            plans. Nothing here limits liability that can&rsquo;t be limited by
            law.
          </p>
        </Section>

        <Section title="Suspension and termination">
          <p>
            You can stop using Astrail and delete your account at any time. We
            may suspend or end access if these terms are breached or to protect
            the service and its users.
          </p>
        </Section>

        <Section title="Changes">
          <p>
            We&rsquo;ll update these terms as Astrail grows beyond beta
            (including when booking arrives) and change the date above. Continued
            use after an update means you accept the new terms.
          </p>
        </Section>

        <Section title="Governing law">
          <p>These terms are governed by the laws of Singapore.</p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about these terms? Email{' '}
            <a
              className="font-medium text-[color:var(--ink-900,#1a1a1a)] underline"
              href={`mailto:${contactEmail}`}
            >
              {contactEmail}
            </a>
            .
          </p>
        </Section>
      </div>
    </main>
  )
}

function Section({
  title,
  children,
}: {
  title: string
  children: React.ReactNode
}) {
  return (
    <section>
      <h2 className="text-xl font-semibold text-[color:var(--ink-900,#1a1a1a)]">
        {title}
      </h2>
      <div className="mt-3">{children}</div>
    </section>
  )
}
